"""Generate compact Unicode property tables for jes folding and invisible_text.

Sources are the Unicode Data Files of one pinned Unicode version, so the tables only
change when UNICODE_VERSION does. The generated modules include the Unicode license
notice required for redistribution.

    python tools/generate_unicode_data.py [--out DIR]
"""

from __future__ import annotations

import argparse
import pathlib
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "jes" / "text"
UNICODE_VERSION = "18.0.0"
NOTICE = f"""\
# Unicode Data Files are under the Unicode License, version 3.0.
# Copyright © Unicode, Inc. All rights reserved.
# https://www.unicode.org/license.txt
#
# Unicode {UNICODE_VERSION}. Generated by tools/generate_unicode_data.py. Do not edit by hand.
"""

UCD = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"
# The security data only has numbered directories for some versions, so this reads
# "latest" and checks the version line inside the file.
SECURITY = "https://www.unicode.org/Public/security/latest"


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def parse_ranges(text: str, property_name: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for raw in text.splitlines():
        if not raw or raw.startswith("#"):
            continue
        left, _, _comment = raw.partition("#")
        fields = [part.strip() for part in left.split(";")]
        if len(fields) < 2 or fields[1] != property_name:
            continue
        span = fields[0]
        if ".." in span:
            start_s, end_s = span.split("..")
            ranges.append((int(start_s, 16), int(end_s, 16)))
        else:
            value = int(span, 16)
            ranges.append((value, value))
    return ranges


def parse_sequences(text: str) -> list[str]:
    sequences: list[str] = []
    for raw in text.splitlines():
        if not raw or raw.startswith("#"):
            continue
        left = raw.split(";", 1)[0].strip()
        if not left:
            continue
        codes = [int(part, 16) for part in left.split() if part]
        if codes:
            sequences.append("".join(chr(code) for code in codes))
    return sequences


def parse_confusables(text: str) -> dict[int, str]:
    mapping: dict[int, str] = {}
    for raw in text.splitlines():
        if not raw or raw.startswith("#"):
            continue
        left = raw.split("#", 1)[0]
        fields = [part.strip() for part in left.split(";")]
        if len(fields) < 2:
            continue
        source = int(fields[0].split()[0], 16)
        target = "".join(chr(int(part, 16)) for part in fields[1].split())
        mapping[source] = target
    return mapping


def emit_ranges(name: str, ranges: list[tuple[int, int]]) -> str:
    items = ",\n    ".join(f"(0x{start:04X}, 0x{end:04X})" for start, end in ranges)
    return f"{name}: tuple[tuple[int, int], ...] = (\n    {items},\n)\n"


def emit_sequences(name: str, sequences: list[str]) -> str:
    unique = sorted(set(sequences), key=lambda item: (len(item), item))
    items = ",\n    ".join(repr(item) for item in unique)
    return f"{name}: frozenset[str] = frozenset((\n    {items},\n))\n"


def emit_confusables(mapping: dict[int, str]) -> str:
    items = ",\n    ".join(f"0x{key:04X}: {value!r}" for key, value in sorted(mapping.items()))
    return f"CONFUSABLES: dict[int, str] = {{\n    {items},\n}}\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=pathlib.Path, default=OUT, help="directory to write")
    out: pathlib.Path = parser.parse_args().out

    derived = fetch(f"{UCD}/DerivedCoreProperties.txt")
    props = fetch(f"{UCD}/PropList.txt")
    variants = fetch(f"{UCD}/StandardizedVariants.txt")
    emoji = fetch(f"{UCD}/emoji/emoji-variation-sequences.txt")
    confusables = fetch(f"{SECURITY}/confusables.txt")
    if f"# Version: {UNICODE_VERSION}\n" not in confusables[:2000]:
        raise SystemExit(f"confusables.txt is not Unicode {UNICODE_VERSION}; update the pin")

    ignorable = parse_ranges(derived, "Default_Ignorable_Code_Point")
    bidi = parse_ranges(props, "Bidi_Control")
    sequences = parse_sequences(variants) + parse_sequences(emoji)
    mapping = parse_confusables(confusables)

    ucd = (
        NOTICE
        + "from __future__ import annotations\n\n"
        + emit_ranges("DEFAULT_IGNORABLE", ignorable)
        + "\n"
        + emit_ranges("BIDI_CONTROL", bidi)
        + "\n"
        + emit_sequences("VARIATION_SEQUENCES", sequences)
    )
    (out / "_ucd_data.py").write_text(ucd, encoding="utf-8")

    conf = NOTICE + "from __future__ import annotations\n\n" + emit_confusables(mapping)
    (out / "_confusables_data.py").write_text(conf, encoding="utf-8")
    print(
        f"wrote {len(ignorable)} ignorable ranges, {len(bidi)} bidi ranges, "
        f"{len(set(sequences))} variation sequences, {len(mapping)} confusables"
    )


if __name__ == "__main__":
    main()
